export const CINEVERSE_BUILD_TAXONOMY = "taxonomy-engine-v1-global-menus";

export const CORE_MOVIE_GENRES = [
  "Acțiune",
  "Horror",
  "Musical",
  "Aventură",
  "Sci-Fi",
  "Fantezie",
  "Mister",
  "Sport",
  "Dramă",
  "Romantism",
  "Comedie"
];

export const ANIME_GENRES = [
  "Acțiune",
  "Aventură",
  "Comedie",
  "Dramă",
  "Fantezie",
  "Horror",
  "Mister",
  "Muzical",
  "Romantic",
  "Sci-Fi",
  "Slice of Life",
  "Sport",
  "Thriller",
  "Mecha",
  "Supernatural",
  "Psychological",
  "Historical",
  "Gore",
  "Ecchi",
  "Isekai",
  "Josei",
  "Seinen",
  "Shoujo-ai",
  "Shounen-ai",
  "Cyberpunk",
  "Post-apocaliptic",
  "Steampunk",
  "Harem",
  "Yuri",
  "Yaoi"
];

export const BOLLYWOOD_GENRES = [
  "Acțiune",
  "Aventură",
  "Comedie",
  "Dramă",
  "Fantezie",
  "Horror",
  "Mister",
  "Muzical",
  "Romantic",
  "Sci-Fi",
  "Thriller",
  "Istoric",
  "Polițist",
  "Biografic",
  "Social",
  "Sport",
  "Mitologic",
  "Satiră",
  "Psihologic",
  "Familie",
  "Suspans",
  "Crime",
  "Epice"
];

export const SPORT_GENRES = [
  "WWE",
  "UFC",
  "MMA",
  "NBA",
  "F1",
  "Football",
  "Box"
];

export const MUSIC_GENRES = [
  "Manele",
  "RNB",
  "Hip Hop",
  "Jazz",
  "Trap",
  "Rap",
  "Reggaeton"
];

export const TV_SHOW_GENRES = [
  "Sci-Fi",
  "Polițist",
  "Entertainment",
  "Reality Show",
  "Talk Show",
  "Documentar",
  "Game Show",
  "Revelion",
  "Culinare",
  "Știri",
  "Supranatural"
];

export const CONTENT_CATEGORIES = [
  "Filme",
  "Seriale",
  "Desene Animate Filme",
  "Desene Animate Seriale",
  "Anime-uri Filme",
  "Anime-uri Seriale",
  "Filme Bollywood",
  "Seriale Bollywood",
  "Filme Desene Dublate",
  "Seriale Desene Dublate",
  "Sport",
  "Muzică",
  "All Collection",
  "Disney",
  "DC",
  "Marvel",
  "Minimax",
  "Cartoon Network",
  "Fox Kids",
  "Nickelodeon",
  "Animax",
  "Boomerang",
  "Disney Junior",
  "Disney Channel",
  "JimJam",
  "Baby TV",
  "Filme Război",
  "Tv Show-uri"
];

export const CATEGORY_GENRES = {
  "Filme": CORE_MOVIE_GENRES,
  "Seriale": CORE_MOVIE_GENRES,
  "Desene Animate Filme": CORE_MOVIE_GENRES,
  "Desene Animate Seriale": CORE_MOVIE_GENRES,
  "Filme Desene Dublate": CORE_MOVIE_GENRES,
  "Seriale Desene Dublate": CORE_MOVIE_GENRES,
  "Filme Război": CORE_MOVIE_GENRES,
  "Disney": CORE_MOVIE_GENRES,
  "DC": CORE_MOVIE_GENRES,
  "Marvel": CORE_MOVIE_GENRES,
  "Minimax": CORE_MOVIE_GENRES,
  "Cartoon Network": CORE_MOVIE_GENRES,
  "Fox Kids": CORE_MOVIE_GENRES,
  "Nickelodeon": CORE_MOVIE_GENRES,
  "Animax": CORE_MOVIE_GENRES,
  "Boomerang": CORE_MOVIE_GENRES,
  "Disney Junior": CORE_MOVIE_GENRES,
  "Disney Channel": CORE_MOVIE_GENRES,
  "JimJam": CORE_MOVIE_GENRES,
  "Baby TV": CORE_MOVIE_GENRES,
  "Anime-uri Filme": ANIME_GENRES,
  "Anime-uri Seriale": ANIME_GENRES,
  "Filme Bollywood": BOLLYWOOD_GENRES,
  "Seriale Bollywood": BOLLYWOOD_GENRES,
  "Sport": SPORT_GENRES,
  "Muzică": MUSIC_GENRES,
  "Tv Show-uri": TV_SHOW_GENRES,
  "All Collection": []
};

export const SOURCE_TYPES = [
  "YouTube",
  "Iframe",
  "Terabox",
  "TikTok",
  "Rumble",
  "Dailymotion",
  "Vimeo",
  "Google / Website",
  "Other URL"
];

export const VIDEO_QUALITIES = [
  "144p",
  "240p",
  "360p",
  "480p",
  "720p",
  "1080p",
  "1440p",
  "2160p",
  "4320p",
  "7680p"
];

export const VIDEO_QUALITY_LABELS = {
  "144p": "144p - Rezoluție foarte joasă",
  "240p": "240p",
  "360p": "360p",
  "480p": "480p - SD",
  "720p": "720p - HD",
  "1080p": "1080p - Full HD",
  "1440p": "1440p - 2K",
  "2160p": "2160p - 4K Ultra HD",
  "4320p": "4320p - 8K",
  "7680p": "7680p - 16K"
};

export const YEARS = Array.from({ length: 2100 - 1950 + 1 }, (_, index) => String(1950 + index));

export const COUNTRIES = [
  "Afganistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua și Barbuda",
  "Arabia Saudită",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaidjan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgia",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia și Herțegovina",
  "Botswana",
  "Brazilia",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodgia",
  "Camerun",
  "Canada",
  "Capul Verde",
  "Republica Centrafricană",
  "Ciad",
  "Chile",
  "China",
  "Cipru",
  "Columbia",
  "Comore",
  "Congo",
  "Republica Democrată Congo",
  "Coreea de Nord",
  "Coreea de Sud",
  "Costa Rica",
  "Coasta de Fildeș",
  "Croația",
  "Cuba",
  "Danemarca",
  "Dominica",
  "Republica Dominicană",
  "Ecuador",
  "Egipt",
  "El Salvador",
  "Emiratele Arabe Unite",
  "Eritreea",
  "Estonia",
  "Eswatini",
  "Etiopia",
  "Fiji",
  "Filipine",
  "Finlanda",
  "Franța",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germania",
  "Ghana",
  "Grecia",
  "Grenada",
  "Guatemala",
  "Guineea",
  "Guineea-Bissau",
  "Guineea Ecuatorială",
  "Guyana",
  "Haiti",
  "Honduras",
  "India",
  "Indonezia",
  "Irak",
  "Iran",
  "Irlanda",
  "Islanda",
  "Israel",
  "Italia",
  "Jamaica",
  "Japonia",
  "Iordania",
  "Kazahstan",
  "Kenya",
  "Kiribati",
  "Kuweit",
  "Kârgâzstan",
  "Laos",
  "Letonia",
  "Liban",
  "Liberia",
  "Libia",
  "Liechtenstein",
  "Lituania",
  "Luxemburg",
  "Madagascar",
  "Malawi",
  "Malaezia",
  "Maldive",
  "Mali",
  "Malta",
  "Maroc",
  "Insulele Marshall",
  "Mauritania",
  "Mauritius",
  "Mexic",
  "Micronezia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Muntenegru",
  "Mozambic",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norvegia",
  "Noua Zeelandă",
  "Oman",
  "Olanda",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua Noua Guinee",
  "Paraguay",
  "Peru",
  "Polonia",
  "Portugalia",
  "Qatar",
  "Regatul Unit",
  "România",
  "Rusia",
  "Rwanda",
  "Saint Kitts și Nevis",
  "Saint Lucia",
  "Saint Vincent și Grenadine",
  "Samoa",
  "San Marino",
  "São Tomé și Príncipe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Siria",
  "Slovacia",
  "Slovenia",
  "Insulele Solomon",
  "Somalia",
  "Africa de Sud",
  "Sudan",
  "Sudanul de Sud",
  "Sri Lanka",
  "Suedia",
  "Elveția",
  "Surinam",
  "Tadjikistan",
  "Tanzania",
  "Thailanda",
  "Timorul de Est",
  "Togo",
  "Tonga",
  "Trinidad și Tobago",
  "Tunisia",
  "Turcia",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ucraina",
  "Ungaria",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

export const LANGUAGES = [
  "Română",
  "Engleză",
  "Franceză",
  "Germană",
  "Spaniolă",
  "Italiană",
  "Portugheză",
  "Hindi",
  "Turcă",
  "Japoneză",
  "Coreeană",
  "Chineză",
  "Arabă",
  "Rusă",
  "Ucraineană",
  "Poloneză",
  "Greacă",
  "Bulgară",
  "Sârbă",
  "Croată",
  "Albaneză",
  "Maghiară",
  "Olandeză",
  "Suedeză",
  "Norvegiană",
  "Daneză",
  "Finlandeză",
  "Ebraică",
  "Persană",
  "Bengali",
  "Urdu",
  "Indoneziană",
  "Malay",
  "Thai",
  "Vietnameză",
  "Filipineză",
  "Swahili",
  "Zulu",
  "Afrikaans"
];

export const SETTINGS_GROUPS = [
  "Cont și Preferințe Utilizator",
  "Setări Video și Audio",
  "Control Parental",
  "Interfață și Personalizare",
  "Conectivitate și Dispozitive",
  "Plăți și Abonamente",
  "Asistență și Feedback",
  "Securitate și Confidențialitate",
  "Accesibilitate",
  "Integrare cu Rețele Sociale"
];

export function getGenresForCategory(category) {
  return CATEGORY_GENRES[category] || CORE_MOVIE_GENRES;
}
